### ISSUE TITLE
navigationBar 중첩 문제

### ISSUE THREAD

**Issue by wodyddml2** [pokemonpedia/Riding_App#12]
### navigationBar 중첩

화면전환 부담을 뷰컨 대신 Coordinator에 위임하기 위해 Coordinator 패턴을 적용하면서 RootViewController를 UINavigationViewController로 설정하면서 rootView의 navigationBar와 tabbar 안의 화면들의 navigationBar가 중첩되는 이슈를 겪게 되었다.

### 해결
RootView의 navigationBar를 Hidden 처리해주고 TabBar의 navigationBar만 화면에 보여줌으로써 해결하였다.

## Before
<img width="200" alt="스크린샷 2023-01-26 오후 6 20 54" src="https://user-images.githubusercontent.com/83345066/214800408-17895dce-f1de-400c-905d-3bf1b53e854c.png">

## After
<img width="200" alt="스크린샷 2023-01-26 오후 6 21 10" src="https://user-images.githubusercontent.com/83345066/214800499-a0f20bca-76ff-434a-a449-cef190f3e094.png">

**Comment by Glsme** [comment]
확인했습니다.
