### ISSUE TITLE
Splash Scene 필요성

### ISSUE THREAD

**Issue by Glsme** [pokemonpedia/Riding_App#8]
Splash가 기존에 AppDelegate나 SceneDelegate에서 네트워크 연결 여부 등 다양한 분기 처리와 이벤트 핸들링을 하기 위해서 만들어진 개념인데,
지금 AppCoordinator가 있음에도 불구하고 한번 더 Splash Scene을 거칠 필요가 있을까 생각했습니다.

---
| 기존 |
|:--:|
| App Coordinator |
| ↓ |
| Splash Coordinator (분기 처리) |
| ↓ |
| Splash ViewController |
| ↓ |
| TabBar Coordinator |

<br/></br>
| 새로운 방법 |
|:--:|
| App Coordinator (분기 처리) |
| ↓ |
| TabBar Coordinator |

위 방법처럼 AppCoordinator에서 바로 분기처리 후,
Login Scene 이나 Main(TabBar) Scene으로 가는게 어떤지 생각합니다.

**Comment by wodyddml2** [comment]
좋은 생각인 것 같습니다.
의견에 따라 프로젝트 수정 진행하겠습니다!
